POST  http://localhost:10000/api/persons
Content-Type: application/json

{
    "name": "Mufidat Wahab",
    "number": 1234
}

###
PUT http://localhost:10000/api/persons/6411fcc4863d4afda951adda
Content-Type: application/json

{
    "name": "Mufidat W",
    "number": 12345
}